version: '3'

services:
  migration:
    build: '.'
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - master:/app/master
    ports:
      - 4080:4080

volumes:
  master:
    driver: local
